name: IPFS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node verison
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Build website
        run: |
          yarn install
          yarn build
      - name: Upload to IPFS
        uses: ipfs-shipyard/ipfs-github-action@v2.0.0
        with:
          path_to_add: dist
          cluster_host: /dnsaddr/cluster.ipfs.io
      - run: echo /ipfs/${{ steps.ipfs.outputs.cid }}
      - run: echo ${{ steps.ipfs.outputs.url }}