name: IPFS

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node verison
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Build website
        run: |
          yarn install
          yarn build
      - name: Upload to IPFS
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: 'Personal Website'
          path: dist
          pinata-api-key: ${{ secrets.PINATA_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
          verbose: true