name: Build static website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node verison
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Build website
        run: |
          yarn install
          yarn build
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Publish on GCP Storage
        run: gsutil -m rsync -d -c -r dist gs://${{ secrets.GCP_BUCKET }}
