name: Build & upload website

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup node verison
        uses: actions/setup-node@v1
        with:
          node-version: '15'
      - name: Build website
        run: |
          yarn install
          yarn build

  gcp:
    name: Upload on GCP
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}
      - name: Publish on GCP Storage
        run: gsutil -m rsync -d -c -r dist gs://${{ secrets.GCP_BUCKET }}

  ipfs:
    name: Upload on IPFS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Pin to IPFS
        id: upload
        uses: anantaramdas/ipfs-pinata-deploy-action@v1.6.3
        with:
          pin-name: 'Personal Website'
          path: dist
          pinata-api-key: ${{ secrets.PINATA_KEY }}
          pinata-secret-api-key: ${{ secrets.PINATA_SECRET }}
          verbose: true
          remove-old: true
      - name: Update DNS with new IPFS hash
        uses: textileio/cloudflare-update-dnslink@v2
        env:
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
          RECORD_DOMAIN: 'voidmx.net'
          RECORD_NAME: '_dnslink.ipfs'
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        with:
          cid: ${{ steps.upload.outputs.hash }}